config/routes.rb
MlbApp::Application.routes.draw do

  
  resources :searches

  resources :manuals

  resources :calendars

  root "replays#new"
  get "contact", to: "pages#contact", as: "contact"
 
  devise_for :users
  resources :users
  

  namespace :admin do
    root "base#index"
    resources :users
     end


 
  resources :replays, :emails, :confirmed, :calendars, :manual, :search
  
   

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
	has_many :replays

	extend SimpleCalendar
  #has_calendar

  # Or set a custom attribute for simple_calendar to sort by
  has_calendar :attribute => :date
	

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendar = Replay.all
    @calendar_by_date = @calendar.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
   
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params[:calendar]
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<div class="">
                <div role="tabpanel" class="" id="replay-review">
                  <h1>Calendar</h1>
                  <%= link_to "Return to Replays", root_path%>
                  <div id="calendar">
                  <h2 id="month">
                    <%= link_to "<", date: @date.prev_month %>
                    <%= @date.strftime("%B %Y") %>
                    <%= link_to ">", date: @date.next_month %>
                  </h2>
                  <%= calendar @date do |date| %>
                    <%= date.day %>
                    <% if @calendar_by_date[date] %>
                      <ul>
                        <% @calendar_by_date[date].each do |calendar| %>
                          <li><%= link_to calendar.visiting_team + "/" + calendar.home_team, replay_path(calendar ,:anchor => "data") %>(<%= link_to calendar.id, replay_path(calendar ,:anchor => "data") %>)</li>
                        <% end %>
                      </ul>
                    <% end %>
                  <% end %>
                </div>
                </div>
              </div>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>