config/routes.rb
MlbApp::Application.routes.draw do

  
  resources :searches

  resources :manuals

  resources :calendars

  root "replays#new"
  get "contact", to: "pages#contact", as: "contact"
 
  devise_for :users
  resources :users
  

  namespace :admin do
    root "base#index"
    resources :users
     end


 
  resources :replays, :emails, :confirmed, :calendars, :manual, :search
  
   

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @replay_date = Replay.all
    #day_offset = Time.now - (24 * 60 * 60) # 24 hours ago
    @all_replays = Replay.where("date >= ?", Date.today)
    @visiting_team = @all_replays.select("DISTINCT ON (visiting_team) *")
    #@all_replays = Replay.where('created_at > ? AND created_at < ?', Date.today, Date.today + 7.hours)
    
   
     #SEARCH GRID
    @grid = initialize_grid(
      Replay, 
      #:include => [ :visiting_team, :home_team],
      :order => 'replays.id',
      :order_direction => 'desc',
      :custom_order => {
        # 'tasks.priority_id' => 'priorities.name',
        #'Replay.visiting_team'   => 'visiting_teams.position',
        #'tasks.project_id'  => 'projects.name'
      }
      )
    @grid_weekly = initialize_grid(
      Replay.where("created_at >= ?", Time.zone.now.beginning_of_week),
       :order => 'replays.id',
       :order_direction => 'desc'
       )

    @all_replays_order = Replay.all
    respond_to do |format|
      format.html
      
      format.csv { send_data @all_replays_order.to_csv }
      format.xls { send_data @all_replays_order.to_csv(col_sep: "\t") }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params[:search]
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<% title("Replay") %>
<ul class="nav nav-tabs main-tabs" role="tablist">
  <li role="presentation" ><%= link_to "Today's Games", replay_path(Replay.last, :anchor => 'data')%></li>
  <li role="presentation" class="active"><%= link_to "Search", searches_path%></li>
</ul>
<div class="tab-content">
      <div role="tabpanel"  class="tab-pane  col-sm-12 fade" id="todays-games">

          <div class="col-sm-4  colPush">
            <%= render partial: "layouts/feed" %>
          </div>

          <div class="col-sm-8 colMain">
            <a id="trig" class="btn-info" style="display:block !important"><i class="fa fa-caret-left"></i></a>
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="hidden"><%= link_to "New Email", emails_path %></li>
            <li role="presentation" class="active"><a href="#replay-review" aria-controls="replay-review" role="tab" data-toggle="tab" aria-expanded="true">New Replay</a></li>
          </ul>
          <div class="tab-content">
                <div role="tabpanel" class="tab-pane col-sm-12 fade" id="email">
                  
                </div>
                
              </div>      

        

         </div>    
    </div>
    <div role="tabpanel" class="tab-pane active fade in" id="search">
      <%= render partial: "layouts/search" %>
     </div>
</div>          

app/views/searches/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Visitor</Data></Cell>
        <Cell><Data ss:Type="String">Home</Data></Cell>
        <Cell><Data ss:Type="String">Time</Data></Cell>
        <Cell><Data ss:Type="String">HP</Data></Cell>
        <Cell><Data ss:Type="String">1B</Data></Cell>
        <Cell><Data ss:Type="String">2B</Data></Cell>
        <Cell><Data ss:Type="String">3B</Data></Cell>
        <Cell><Data ss:Type="String">Replay Official</Data></Cell>
        <Cell><Data ss:Type="String">Inning</Data></Cell>
        <Cell><Data ss:Type="String">Score</Data></Cell>
        <Cell><Data ss:Type="String">In Favor Of</Data></Cell>
        <Cell><Data ss:Type="String">Outs</Data></Cell>
        <Cell><Data ss:Type="String">Runners</Data></Cell>
        <Cell><Data ss:Type="String">Challenge</Data></Cell>
        <Cell><Data ss:Type="String">Calling Umpire</Data></Cell>
        <Cell><Data ss:Type="String">Play Description</Data></Cell>
        <Cell><Data ss:Type="String">Play Type</Data></Cell>
        <Cell><Data ss:Type="String">Play Location</Data></Cell>
        <Cell><Data ss:Type="String">Headset Umpire 1</Data></Cell>
        <Cell><Data ss:Type="String">Headset Umpire 2</Data></Cell>
        <Cell><Data ss:Type="String">Replay Offical Ruling</Data></Cell>
        <Cell><Data ss:Type="String">Home</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= replay.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= replay.date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= replay.visiting_team %></Data></Cell>
        <Cell><Data ss:Type="String"><%= replay.home_team %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>