config/routes.rb
MlbApp::Application.routes.draw do

  
  resources :searches

  resources :manuals

  resources :calendars

  root "replays#new"
  get "contact", to: "pages#contact", as: "contact"
 
  devise_for :users
  resources :users
  

  namespace :admin do
    root "base#index"
    resources :users
     end


 
  resources :replays, :emails, :confirmed, :calendars, :manual, :search
  
   

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!

  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count
  end
end

app/views/admin/base/index.html.erb
<% title("Admin") %>
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-3"><h4><%#= link_to "Create New User", new_user_path, :class => "btn lrg-btn btn-info" %>
    <br><br><%= link_to "Back to Replays", root_path, :class => "" %></h4>
  </div>
  <div class="col-sm-9">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count, 'user')}" %></small></h4>
    
    <hr/>
    <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>
  </div>

  

</div>