config/routes.rb
MlbApp::Application.routes.draw do

  
  resources :searches

  resources :manuals

  resources :calendars

  root "replays#new"
  get "contact", to: "pages#contact", as: "contact"
 
  devise_for :users
  resources :users
  

  namespace :admin do
    root "base#index"
    resources :users
     end


 
  resources :replays, :emails, :confirmed, :calendars, :manual, :search
  
   

end

app/views/layouts/_confirm.html.erb
<div class=" confirmed-ruling">
<% if @confirmed.confirmed_ruling.present? %>	
	<%= simple_form_for @confirmed,:url => { :controller => "confirmed", :action => "update" } do |r| %>
		<div class="verify-fields" >
			<%=r.select :confirmation_official, ["Baker","Barksdale","Barber","Barrett, L.","Barrett, T.","Barry","Basner","Bellino","Blaser","Buckminster","Bucknor","Byrne","Campos","Carapazza","Carlson","Cederstrom","Conroy","Cooper","Culbreth","Cuzzi","Danley","Davidson","Davis","DeMuth","Diaz","DiMuro","Drake","Dreckman","Eddings","Emmel","Estabrook","Everitt","Fagan","Fairchild","Fletcher","Foster","Gibson, G.","Gibson, H.","Gonzalez","Gorman","Gosney","Guccione","Hallion","Hamari","Hernandez","Hickox","Hirschbeck","Hoberg","Holbrook","Hoye","Hudson","Iassogna","Johnson, Ad.","Johnson, An.","Joyce","Kellogg","Knight","Kulpa","Layne","Little","Marquez","May","Meals","Miller","Morales","Muchlinski","Nauert","Nelson","O'Nora","Pattillo","Porter","Rackley","Randazzo","Reyburn","Reynolds","Ripperger","Scheurwater","Schrieber","Scott","Segal","Tichenor","Timmons","Tumpane","Vanover","Wegner","Welke, B.","Welke, T.","Wendelstedt","West","Whitson","Winters","Wolcott","Wolf","Woodring"],{}, {:disabled => true} %>
			<%= r.select :confirmed_ruling, ["Confirmed","Stands","Overturned","Record Keeping"],{}, {:disabled => true} %>
		</div>
</div>  

<div class=" confirm-ruling-submit">
	<%= r.submit "Verified", {:class => "btn disabled btn-success verify-ruling lrg-btn"} %>
	<% end %>
	
</div>
<% else %>
	<%= simple_form_for @confirmed,:url => { :controller => "confirmed", :action => "update" } do |r| %>
		<div class="verify-fields" >
			<%=r.select :confirmation_official, ["Baker","Barksdale","Barber","Barrett, L.","Barrett, T.","Barry","Basner","Bellino","Blaser","Buckminster","Bucknor","Byrne","Campos","Carapazza","Carlson","Cederstrom","Conroy","Cooper","Culbreth","Cuzzi","Danley","Davidson","Davis","DeMuth","Diaz","DiMuro","Drake","Dreckman","Eddings","Emmel","Estabrook","Everitt","Fagan","Fairchild","Fletcher","Foster","Gibson, G.","Gibson, H.","Gonzalez","Gorman","Gosney","Guccione","Hallion","Hamari","Hernandez","Hickox","Hirschbeck","Hoberg","Holbrook","Hoye","Hudson","Iassogna","Johnson, Ad.","Johnson, An.","Joyce","Kellogg","Knight","Kulpa","Layne","Little","Marquez","May","Meals","Miller","Morales","Muchlinski","Nauert","Nelson","O'Nora","Pattillo","Porter","Rackley","Randazzo","Reyburn","Reynolds","Ripperger","Scheurwater","Schrieber","Scott","Segal","Tichenor","Timmons","Tumpane","Vanover","Wegner","Welke, B.","Welke, T.","Wendelstedt","West","Whitson","Winters","Wolcott","Wolf","Woodring"], {:class => "hidden", :style => "width:auto"} %>
			<%= r.select :confirmed_ruling, ["Confirmed","Stands","Overturned","Record Keeping"], {:class => "btn disabled btn-info verify-ruling lrg-btn", :style => "width:auto"}%>
		</div>
</div>  

<div class=" confirm-ruling-submit">
	<%= r.submit "Verify Ruling", :class => "btn btn-info verify-ruling lrg-btn", data: { confirm: "Please confirm you want to send the email?" } %>

	<% end %>
	
</div>
<% end %>
<p></p>

app/views/layouts/_data_entries.html.erb
<div style="clear:both">
  <h1>Replay #<%= @this_replay.id %> <button style="font-size:12px;float:right"><%=link_to_if current_user.id <= 11, "Edit Replay", edit_replay_path(@this_replay)%></button></h1>
 
<table class="tg" style="undefined;table-layout: fixed;">
<colgroup>
<col style="col-sm-4">
<col style="col-sm-4">
</colgroup>
  <tr>
    <td class="tg-tvhl">Type of Challenge</th>
    <td class="tg-1u2s"><%= @this_replay.type_of_challenge %></th>
  </tr>
  <tr>
    <td class="tg-3768">Play Type</td>
    <td class="tg-031e"><%= @this_replay.play_type %></td>
  </tr>
  <% if @this_replay.homerun_variation.present? %>
  <tr>
    <td class="tg-tvhl">Home Run Variation</th>
    <td class="tg-1u2s"><%= @this_replay.homerun_variation %></th>
  </tr>
  <%end%>
  <% if @this_replay.tag_play_variation.present? %>
  <tr>
    <td class="tg-3768">Tag Play Variation</td>
    <td class="tg-031e"><%= @this_replay.tag_play_variation if @this_replay.tag_play_variation.present? %></td>
  </tr>
  <%end%>
  <% if @this_replay.force_play_variation.present? %>
  <tr>
    <td class="tg-3768">Force Play Variation</td>
    <td class="tg-031e"><%= @this_replay.force_play_variation if @this_replay.force_play_variation.present? %></td>
  </tr>
  <%end%>
  <% if @this_replay.hit_by_pitch_variation.present? %>
  <tr>
    <td class="tg-3768">Hit By Pitch Variation</td>
    <td class="tg-031e"><%= @this_replay.hit_by_pitch_variation if @this_replay.hit_by_pitch_variation.present? %></td>
  </tr>
  <%end%>
  <% if @this_replay.fair_foul_variation.present? %>
  <tr>
    <td class="tg-3768">Fair / Foul Variation</td>
    <td class="tg-031e"><%= @this_replay.fair_foul_variation if @this_replay.fair_foul_variation.present? %></td>
  </tr>
  <%end%>
  <% if @this_replay.violation_of_collision_variation.present? %>
  <tr>
    <td class="tg-3768">Violation of Collision at Home Plate Variation</td>
    <td class="tg-031e"><%= @this_replay.violation_of_collision_variation if @this_replay.violation_of_collision_variation.present? %></td>
  </tr>
  <%end%>
  <% if @this_replay.catch_no_catch_variation.present? %>
  <tr>
    <td class="tg-3768">Catch / No Catch Variation</td>
    <td class="tg-031e"><%= @this_replay.catch_no_catch_variation if @this_replay.catch_no_catch_variation.present? %></td>
  </tr>
  <%end%>

  <tr>
    <td class="tg-tvhl">Original Ruling on Field</td>
    <td class="tg-1u2s"><%= @this_replay.orig_ruling_on_field %></td>
  </tr>
  <tr>
    <td class="tg-3768">Replay Official Ruling</td>
    <td class="tg-031e"><%= @this_replay.replay_official_ruling %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Visiting Team</th>
    <td class="tg-1u2s"><%= @this_replay.visiting_team %></th>
  </tr>
  <tr>
    <td class="tg-3768">Home Team</td>
    <td class="tg-efv9"><%= @this_replay.home_team %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Game Start Time</td>
    <td class="tg-1u2s"><%= @this_replay.game_start_time.strftime("%I:%M %p") %></td>
  </tr>
  <tr>
    <td class="tg-3768">HP Umpire</td>
    <td class="tg-efv9"><%= @this_replay.hp_umpire %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">1B Umpire</td>
    <td class="tg-1u2s"><%= @this_replay.first_b_umpire %></td>
  </tr>
  <tr>
    <td class="tg-3768">2B Umpire</td>
    <td class="tg-efv9"><%= @this_replay.second_b_umpire %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">3B Umpire</td>
    <td class="tg-1u2s"><%= @this_replay.third_b_umpire %></td>
  </tr>
  <tr>
    <td class="tg-3768">Replay Official</td>
    <td class="tg-efv9"><%= @this_replay.replay_official %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Inning</td>
    <td class="tg-1u2s"><%= @this_replay.inning %></td>
  </tr>
  <tr>
    <td class="tg-3768">Score</td>
    <td class="tg-efv9"><%= @this_replay.score %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">In Favor Of</td>
    <td class="tg-1u2s"><%= @this_replay.in_favor_of %></td>
  </tr>
  <tr>
    <td class="tg-3768">Outs</td>
    <td class="tg-031e"><%= @this_replay.outs %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Runner(s) On</td>
    <td class="tg-1u2s"><%= @this_replay.runners_on %></td>
  </tr>
  
 <tr>
    <td class="tg-3768">Game Date</td>
    <td class="tg-efv9"><%= @this_replay.date.strftime("%m/%d/%Y") %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Calling Umpire</td>
    <td class="tg-1u2s"><%= @this_replay.calling_umpire %></td>
  </tr>
  <tr>
    <td class="tg-3768">Play Description</td>
    <% if @get_replay_email.present? %>
    <td class="tg-031e"><%= @get_replay_email.message %></td>
    <%end%>
  </tr>
  <tr>
    <td class="tg-tvhl">Headset Ump 1</td>
    <td class="tg-1u2s"><%= @this_replay.headset_ump1 %></td>
  </tr>
  <tr>
    <td class="tg-3768">Headset Ump 2</td>
    <td class="tg-031e"><%= @this_replay.headset_ump2 %></td>
  </tr>
  
  <tr>
    <td class="tg-tvhl">Placement of Runners</td>
    <td class="tg-1u2s"><%= @this_replay.placement_of_runners %></td>
  </tr>
  <tr>
    <td class="tg-3768">Was Ruling Correct?</td>
    <td class="tg-031e"><%= @this_replay.was_ruling_correct %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Time from call to review</td>
    <td class="tg-1u2s"><%= @this_replay.time_from_call_to_review%></td>
  </tr>
  <tr>
    <td class="tg-3768">Time on headset</td>
    <td class="tg-031e"><%= @this_replay.time_on_headset %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Time from call to next pitch</td>
    <td class="tg-1u2s"><%= @this_replay.time_from_call_to_next_pitch %></td>
  </tr>
   <tr>
    <td class="tg-3768">Challenging Team</td>
    <td class="tg-031e"><%= @this_replay.challenging_team %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Time from review to ruling</td>
    <td class="tg-1u2s"><%= @this_replay.time_from_review_to_ruling %></td>
  </tr>
  <tr>
    <td class="tg-3768">Time of play</td>
    <% if @this_replay.time_of_play.present? %>
    <td class="tg-031e"><%= @this_replay.time_of_play.strftime("%I:%M %p") %></td>
    <%end%>
  </tr>
  <tr>
    <td class="tg-tvhl">Play Location</td>
    <td class="tg-1u2s"><%= @this_replay.play_location %></td>
  </tr>
  <tr>
    <td class="tg-3768">Stadium</td>
    <td class="tg-031e"><%= @this_replay.stadium %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Admin</td>
    <td class="tg-1u2s"><%= @this_replay.admin %></td>
  </tr>
  <tr>
    <td class="tg-3768">Replay Tech</td>
    <td class="tg-031e"><%= @this_replay.replay_tech %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Definitive Angle</td>
    <td class="tg-1u2s"><%= @this_replay.definitive_angle %></td>
  </tr>
  <tr>
    <td class="tg-3768">Cameras Available</td>
    <td class="tg-031e"><%= @this_replay.cameras_available %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Notes</td>
    <td class="tg-1u2s"><%= @this_replay.notes %></td>
  </tr>
  <tr>
    <td class="tg-3768">Video Link</td>
    <td class="tg-031e"><%= @this_replay.video_link %></td>
  </tr>
  <tr>
    <td class="tg-tvhl">Screenshot Link</td>
    <td class="tg-1u2s"><a target="_blank" href="<%= @this_replay.screenshot_link %>"><%= @this_replay.screenshot_link %></a></td>
  </tr>

</table>
</div>

app/views/layouts/_feed.html.erb
<div class="new-replay-header">
    <div class="feed-datepicker" style="float:left; margin-right:20px;">
     
    
    <% if current_user.id.nil? %>
      <%redirect_to root_path%>
      
      <% else%>
      <% if current_user.id == 1  %> 
        <%= link_to raw('<button class="fa fa-calendar" style="float:left;position:relative"></button>'), calendars_path%>
      <%end%>
    <% end %>
    </div>
    <div class="feed-sort ">
      <%= radio_button_tag(:matchup, "1", true) %><%= label_tag(:matchup, "Matchup") %>
      <%= radio_button_tag(:matchup, "2") %><%= label_tag(:replay, "Replay") %>
   </div>
   <div class="">
    <span class=""><%= link_to_if current_user.id <= 11, "<i class='fa fa-plus-square fa-2' value='New Replay'></i>".html_safe, root_path %></span>
    </div>

</div>
<div class="sidebar">
    <div id="blk-1" class="toHide" >
      <div class="panel-group" id="accordion">
      
        <div class="panel-group" id="accordion">
      <% @visiting_team.each_with_index do |t, index|%>
            <div class="panel panel-default">
              
              <div class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+1 %>">
                <h4 class="panel-title">
                  

                    <%= t.visiting_team %> vs <%= t.home_team %>

                  
                </h4>
                </a>
              </div>
              
              <div id="collapse<%= index+1 %>" class="panel-collapse collapse">
                <% @all_replays.where("visiting_team" => t.visiting_team).each do |i|%>
                <div class="panel-body blue-box">
                  <%= link_to(i) do %>
                  <h4>Replay ID# <%=i.id%> <small><%= i.date.strftime("%m/%d/%Y") %> </small></h4>
                  
                  <p><strong>Play Type:</strong> <%= i.play_type%></p>
                  <p><strong>Challenge Type:</strong> <%= i.type_of_challenge%></p>
                  <p><strong>Call On Field:</strong> <%= i.orig_ruling_on_field%></p>
                  <p><strong>Replay Official Ruling:</strong> <%= i.replay_official_ruling%></p>
                   <%end%>
                   &nbsp;<%=link_to raw('<i class="fa fa-trash-o"></i>'), i, method: :delete, data: { confirm: "Are you sure?" },:title => "Delete Replay"%>
                </div>
               <%end%>
              </div>
            </div>
          <%end%>
      </div>
      </div>
    </div>
    <div id="blk-2" class="toHide" style="display:none">
      <div class="panel-group" id="accordion">
      <% @all_replays.each_with_index do |i, index| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index+ 200 %>">
              <h4 class="panel-title">
                
                  Replay ID# <%= i.id %>
                
              </h4>
              </a>
            </div>
            <div id="collapse<%= index+200 %>" class="panel-collapse collapse">
              <div class="panel-body">
                <h4>Replay ID# <%=i.id%> <small><%= i.date.strftime("%d/%m/%Y") %></small></h4>
                <p><strong>Umpires:</strong><br>HP: <%= i.hp_umpire %> 1B: <%= i.first_b_umpire %> 2B: <%= i.second_b_umpire %> 3B: <%= i.third_b_umpire %></p>
                <p><strong>Start Time:</strong> <%= i.game_start_time.strftime("%I:%M %p")%></p>
                <p><strong>Stadium:</strong> <%= i.stadium%></p>
                <p><strong>Admin:</strong> <%= i.admin%></p>
                <p><strong>Replay Technician:</strong> <%= i.replay_tech%></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
      </div>

    </div>

  </div>
</div>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXXX-XX', 'auto');
ga('send', 'pageview');
</script>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "New User", new_user_registration_path %></li>

<% else %>


<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/_search.html.erb
<ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#game-summaries" aria-controls="game-summaries" role="tab" data-toggle="tab" aria-expanded="true">Game Summaries</a></li>
        <li role="presentation" class=""><a href="#summary" aria-controls="summary" role="tab" data-toggle="tab" aria-expanded="false">Summary</a></li>
        <li role="presentation" class=""><a href="#weekly-summary" aria-controls="weekly-summary" role="tab" data-toggle="tab" aria-expanded="false">Weekly Summary</a></li>
      </ul>
      <div class="tab-content search-panel">
        <div role="tabpanel" class="tab-pane active col-sm-12 fade in" id="game-summaries">
          <div><%= link_to "Export XLS", "replays.xls", :class => "btn-default btn" %>&nbsp;<%= link_to "Export CSV", "replays.csv", :class => "btn-default btn" %></div><Br>
          <div class="row">
            <%= 
              grid(@grid) do |g|
                 g.column name: 'ID', attribute: 'id', filter:false do |p|
                  link_to(p.id, replay_path(p))
                 end
                 g.column name:'Date', attribute: 'date'  do |p|
                   p.date.strftime("%m/%d/%Y")
                 end
                 g.column name: 'Visiting Team',attribute: 'visiting_team', custom_filter: %w(BAL BOS CWS CLE DET TEX KC LAA MIN NYY OAK SEA TB HOU TOR ARI ATL CHC CIN COL LAD MIA MIL NYM SD PIT PHI SF STL WAS) do |p|
                   p.visiting_team
                 end
                 g.column name: 'Home Team',attribute: 'home_team', custom_filter: %w(BAL BOS CWS CLE DET TEX KC LAA MIN NYY OAK SEA TB HOU TOR ARI ATL CHC CIN COL LAD MIA MIL NYM SD PIT PHI SF STL WAS) do |p|
                   p.home_team
                 end
                 g.column name: 'HP Umpire',attribute: 'hp_umpire' do |p|
                   p.hp_umpire
                 end
                 g.column name: '1B Umpire',attribute: 'first_b_umpire' do |p|
                   p.first_b_umpire
                 end
                 g.column name: '2B Umpire',attribute: 'second_b_umpire' do |p|
                   p.second_b_umpire
                 end
                 g.column name: '3B Umpire',attribute: 'third_b_umpire'  do |p|
                   p.third_b_umpire
                 end
                 g.column name: 'Replay Official',attribute: 'replay_official' do |p|
                   p.replay_official
                 end
                 g.column name: 'Game Start Time' do |p|
                   p.game_start_time.strftime("%I:%M %p")
                 end
                 g.column name: 'Stadium' do |p|
                   p.stadium
                 end
                 g.column name: 'Inning' do |p|
                   p.inning
                 end
                 g.column name: 'Score' do |p|
                   p.score
                 end
                 g.column name: 'In Favor Of' do |p|
                   p.in_favor_of
                 end
                 g.column name: 'Outs' do |p|
                   p.outs
                 end
                 g.column name: 'Runners On' do |p|
                   p.runners_on
                 end
                 g.column name: 'Challenging Team',attribute: 'challenging_team', custom_filter: %w(BAL BOS CWS CLE DET TEX KC LAA MIN NYY OAK SEA TB HOU TOR ARI ATL CHC CIN COL LAD MIA MIL NYM SD PIT PHI SF STL WAS) do |p|
                   p.challenging_team
                 end
                 g.column name: 'Calling Umpire' do |p|
                   p.calling_umpire
                 end
                  g.column name: 'Play Desc' do |p|
                   link_to("Click for Description", replay_path(p ,:anchor => "data") )
                 end
                 g.column name: 'Headset Ump 1' do |p|
                   p.headset_ump1
                 end
                 g.column name: 'Headset Ump 2' do |p|
                   p.headset_ump1
                 end
                 g.column name: 'Orginal Ruling on Field' do |p|
                   p.orig_ruling_on_field
                 end
                 g.column name: 'Replay Official Ruling',attribute: 'replay_official_ruling' do |p|
                   p.replay_official_ruling
                 end
                 g.column name: 'Placement of Runners' do |p|
                   p.placement_of_runners
                 end
                 g.column name: 'Was Ruling Correct?' do |p|
                   p.was_ruling_correct
                 end
                 g.column name: 'Play Location',attribute: 'play_location', custom_filter: %w(HP
1B
2B
3B
LF
CF
RF) do |p|
                   p.play_location
                 end
                 g.column name: 'Time of Play' do |p|
                   p.time_of_play
                 end

                 g.column name: 'Time from call to review' do |p|
                   p.time_from_call_to_review
                 end
                 g.column name: 'Time on headset' do |p|
                   p.time_on_headset
                 end
                 g.column name: 'Time from call to next pitch' do |p|
                   p.time_from_call_to_next_pitch
                 end
                 g.column name: 'Time from review to ruling' do |p|
                   p.time_from_review_to_ruling
                 end
                 g.column name: 'Cameras Available' do |p|
                   p.cameras_available
                 end
                 g.column name: 'Definitive Angle' do |p|
                   p.definitive_angle
                 end
                 g.column name: 'Screenshot Link' do |p|
                   p.screenshot_link
                 end
                 
                 g.column name: 'Video Link' do |p|
                   p.video_link
                 end
                 
                 g.column name: 'Admin' do |p|
                   p.admin
                 end
                 g.column name: 'Replay Tech' do |p|
                   p.replay_tech
                 end
              end
           %>
                    
          </div>
        </div>
        <div role="tabpanel" class="tab-pane col-sm-12 fade" id="summary">
          <div class="row">
          </div>
        </div>
        <div role="tabpanel" class="tab-pane col-sm-12 fade" id="weekly-summary">
          <div class="row">
            <%= 
              grid(@grid_weekly) do |g|
                 g.column name: 'ID', attribute: 'id', filter:false do |p|
                  link_to(p.id, replay_path(p))
                 end
                 g.column name:'Date', attribute: 'date'  do |p|
                   p.date.strftime("%m/%d/%Y")
                 end
                 g.column name: 'Visiting Team',attribute: 'visiting_team', custom_filter: %w(BAL BOS CWS CLE DET TEX KC LAA MIN NYY OAK SEA TB HOU TOR ARI ATL CHC CIN COL LAD MIA MIL NYM SD PIT PHI SF STL WAS) do |p|
                   p.visiting_team
                 end
                 g.column name: 'Home Team',attribute: 'home_team', custom_filter: %w(BAL BOS CWS CLE DET TEX KC LAA MIN NYY OAK SEA TB HOU TOR ARI ATL CHC CIN COL LAD MIA MIL NYM SD PIT PHI SF STL WAS) do |p|
                   p.home_team
                 end
                 g.column name: 'HP Umpire',attribute: 'hp_umpire' do |p|
                   p.hp_umpire
                 end
                 g.column name: '1B Umpire',attribute: 'first_b_umpire' do |p|
                   p.first_b_umpire
                 end
                 g.column name: '2B Umpire',attribute: 'second_b_umpire' do |p|
                   p.second_b_umpire
                 end
                 g.column name: '3B Umpire',attribute: 'third_b_umpire'  do |p|
                   p.third_b_umpire
                 end
                 g.column name: 'Replay Official',attribute: 'replay_official' do |p|
                   p.replay_official
                 end
                 g.column name: 'Game Start Time' do |p|
                   p.game_start_time.strftime("%I:%M %p")
                 end
                 g.column name: 'Inning' do |p|
                   p.inning
                 end
                 g.column name: 'Score' do |p|
                   p.score
                 end
                 g.column name: 'In Favor Of' do |p|
                   p.in_favor_of
                 end
                 g.column name: 'Outs' do |p|
                   p.outs
                 end
                 g.column name: 'Runners On' do |p|
                   p.runners_on
                 end
                 g.column name: 'Challenging Team' do |p|
                   p.challenging_team
                 end
                 g.column name: 'Calling Umpire' do |p|
                   p.calling_umpire
                 end
                 g.column name: 'Play Desc' do |p|
                   link_to("Click for Description", replay_path(p ,:anchor => "data") )
                 end
                 g.column name: 'Headset Ump 1' do |p|
                   p.headset_ump1
                 end
                 g.column name: 'Headset Ump 2' do |p|
                   p.headset_ump1
                 end
                 g.column name: 'Orginal Ruling on Field' do |p|
                   p.orig_ruling_on_field
                 end
                 g.column name: 'Replay Official Ruling',attribute: 'play_location', custom_filter: %w(Confirmed
Stands
Overturned) do |p|
                   p.replay_official_ruling
                 end
                 g.column name: 'Placement of Runners' do |p|
                   p.placement_of_runners
                 end
                 g.column name: 'Was Ruling Correct?' do |p|
                   p.was_ruling_correct
                 end
                 g.column name: 'Play Location' do |p|
                   p.play_location
                 end
                 g.column name: 'Time of Play' do |p|
                   p.time_of_play
                 end
                 g.column name: 'Time from call to review' do |p|
                   p.time_from_call_to_review
                 end
                 g.column name: 'Time on headset' do |p|
                   p.time_on_headset
                 end
                 g.column name: 'Time from call to next pitch' do |p|
                   p.time_from_call_to_next_pitch
                 end
                 g.column name: 'Time from review to ruling' do |p|
                   p.time_from_review_to_ruling
                 end
                 
                 g.column name: 'Admin' do |p|
                   p.admin
                 end
                 g.column name: 'Replay Tech' do |p|
                   p.replay_tech
                 end
                 g.column name: 'Cameras Available' do |p|
                   p.cameras_available
                 end
                 g.column name: 'Definitive Angle' do |p|
                   p.definitive_angle
                 end
                 g.column name: 'Screenshot Link' do |p|
                   link_to (p.screenshot_link)
                 end
                 
                 g.column name: 'Video Link' do |p|
                   link_to (p.video_link)
                 end
                 
                 g.column name: 'Admin' do |p|
                   p.admin
                 end
                 g.column name: 'Replay Tech' do |p|
                   p.replay_tech
                 end
               end
               %>
          </div>
        </div>
      </div>

      